<a href="https://colab.research.google.com/github/Nitish-9k/MultiClass_classsification_using_NN/blob/main/MulticlassClassificationusingANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,Dataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [8]:
df=pd.read_csv("df.csv")
df

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,255403,1925.3650,691.8453,477.1796,0.7241,570.2536,0.9785,261028,0.7269,1.4499,...,2.2423,2.3704,2.7202,-25296416768,-19168882688,-18473392128,49.0869,43.0422,42.4153,SOGAY
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502,SOGAY
895,254330,1926.7360,747.4943,435.6219,0.8126,569.0545,0.9925,256255,0.7240,1.7159,...,2.2759,2.5090,2.6951,-22242772992,-19594921984,-17592152064,44.1325,40.7986,40.9769,SOGAY
896,238955,1906.2679,716.6485,441.8297,0.7873,551.5859,0.9604,248795,0.6954,1.6220,...,2.6769,2.6874,2.7991,-26048595968,-21299822592,-19809978368,51.2267,45.7162,45.6260,SOGAY
897,343792,2289.2720,823.8438,534.7757,0.7607,661.6113,0.9781,351472,0.6941,1.5405,...,2.5138,3.0369,3.0865,-31983476736,-20482514944,-21219354624,47.3454,38.6966,39.6738,SOGAY

In [9]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [10]:
df.columns

Index(['AREA', 'PERIMETER', 'MAJOR_AXIS', 'MINOR_AXIS', 'ECCENTRICITY',
       'EQDIASQ', 'SOLIDITY', 'CONVEX_AREA', 'EXTENT', 'ASPECT_RATIO',
       'ROUNDNESS', 'COMPACTNESS', 'SHAPEFACTOR_1', 'SHAPEFACTOR_2',
       'SHAPEFACTOR_3', 'SHAPEFACTOR_4', 'MeanRR', 'MeanRG', 'MeanRB',
       'StdDevRR', 'StdDevRG', 'StdDevRB', 'SkewRR', 'SkewRG', 'SkewRB',
       'KurtosisRR', 'KurtosisRG', 'KurtosisRB', 'EntropyRR', 'EntropyRG',
       'EntropyRB', 'ALLdaub4RR', 'ALLdaub4RG', 'ALLdaub4RB', 'Class'],
      dtype='object')

In [11]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [12]:
df = pd.read_csv("df.csv")
le=LabelEncoder()
x=df.drop("Class",axis=1)
y=df["Class"]

y=le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
se=StandardScaler()
x_train_scaled=se.fit_transform(x_train)
x_test_scaled=se.transform(x_test)

## **ANN**

In [15]:
# Tensors
X_train_tensors=torch.tensor(x_train_scaled,dtype=torch.float32)
y_train_tensors=torch.tensor(y_train,dtype=torch.long)

X_test_tensors=torch.tensor(x_test_scaled,dtype=torch.float32)
y_test_tensors=torch.tensor(y_test,dtype=torch.long)

In [16]:
# dataset
train_dataset=torch.utils.data.TensorDataset(X_train_tensors,y_train_tensors)
test_dataset=torch.utils.data.TensorDataset(X_test_tensors,y_test_tensors)

In [17]:
# dataloader class
train_dataloader=torch.utils.data.DataLoader(train_dataset,batch_size=,32shuffle=True)
test_dataloader=torch.utils.data.DataLoader(test_dataset,batch_size=32,shuffle=False)

In [23]:
# model
class Ann(nn.Module):
  def __init__(self):
    super(Ann,self).__init__()
    self.model=nn.Sequential(
        nn.Linear(x.shape[1],64),
        nn.ReLU(),
        nn.Linear(64,64),
        nn.ReLU(),
        nn.Linear(64,7),
    )
  def forward(self,x):
    return self.model(x)

In [24]:
model=Ann()
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [27]:
epochs=100
for epoch in range(epochs):
  model.train()
  running_loss=0.0
  for xb,yb in train_dataloader:
    output=model(xb)
    loss=criterion(output,yb)
    loss.backward()
    optimizer.step()
    running_loss+=loss.item()

  epoch_loss=running_loss/len(train_dataloader)

  print(f"for {epoch/epochs} ==>>  loss:{running_loss} ")

for 0.01 ==>>  loss:73.76771116256714
for 1.01 ==>>  loss:40.26036222279072
for 2.01 ==>>  loss:27.33330012857914
for 3.01 ==>>  loss:38.17583182454109
for 4.01 ==>>  loss:45.06303273886442
for 5.01 ==>>  loss:50.344818495213985
for 6.01 ==>>  loss:50.45649096369743
for 7.01 ==>>  loss:40.69072346389294
for 8.01 ==>>  loss:37.37232185900211
for 9.01 ==>>  loss:27.82449819147587
for 10.01 ==>>  loss:27.562464259564877
for 11.01 ==>>  loss:32.19528470933437
for 12.01 ==>>  loss:27.59358736872673
for 13.01 ==>>  loss:33.41713248193264
for 14.01 ==>>  loss:25.870003156363964
for 15.01 ==>>  loss:32.71931913122535
for 16.01 ==>>  loss:25.13910286128521
for 17.01 ==>>  loss:24.263406425714493
for 18.01 ==>>  loss:24.382276117801666
for 19.01 ==>>  loss:20.921845212578773
for 20.01 ==>>  loss:23.37412871606648
for 21.01 ==>>  loss:23.030481096357107
for 22.01 ==>>  loss:21.49683754146099
for 23.01 ==>>  loss:19.04890649020672
for 24.01 ==>>  loss:21.374074982479215
for 25.01 ==>>  loss:21.21793844597414
for 26.01 ==>>  loss:16.89855327422265
for 27.01 ==>>  loss:20.191508695483208
for 28.01 ==>>  loss:22.630949991755188
for 29.01 ==>>  loss:20.50732739176601
for 30.01 ==>>  loss:20.664174279663712
for 31.01 ==>>  loss:18.826826434582472
for 32.01 ==>>  loss:18.542794696986675
for 33.01 ==>>  loss:21.399926646612585
for 34.01 ==>>  loss:19.79322667926317
for 35.01 ==>>  loss:28.387887459248304
for 36.01 ==>>  loss:25.77234565465551
for 37.01 ==>>  loss:30.063905462622643
for 38.01 ==>>  loss:52.886663280427456
for 39.01 ==>>  loss:54.618062034249306
for 40.01 ==>>  loss:47.903606086969376
for 41.01 ==>>  loss:36.048470962792635
for 42.01 ==>>  loss:36.35800876887515
for 43.01 ==>>  loss:41.66692444309592
for 44.01 ==>>  loss:32.97959331409402
for 45.01 ==>>  loss:30.38765899837017
for 46.01 ==>>  loss:38.05727222748101
for 47.01 ==>>  loss:28.13494860008359
for 48.01 ==>>  loss:31.706947058439255
for 49.01 ==>>  loss:40.388091549277306
for 50.01 ==>>  loss:53.350010335445404
for 51.01 ==>>  loss:37.9768569432199
for 52.01 ==>>  loss:28.18894352018833
for 53.01 ==>>  loss:22.328135646879673
for 54.01 ==>>  loss:29.252120941877365
for 55.01 ==>>  loss:37.08972877264023
for 56.01 ==>>  loss:35.570076517760754
for 57.01 ==>>  loss:27.653307624161243
for 58.01 ==>>  loss:23.337829239666462
for 59.01 ==>>  loss:28.835681661963463
for 60.01 ==>>  loss:29.807887241244316
for 61.01 ==>>  loss:27.503267213702202
for 62.01 ==>>  loss:26.34125255048275
for 63.01 ==>>  loss:29.04219055165595
for 64.01 ==>>  loss:29.421683371067047
for 65.01 ==>>  loss:31.054205909371376
for 66.01 ==>>  loss:32.55070589482784
for 67.01 ==>>  loss:30.89231875538826
for 68.01 ==>>  loss:30.03248006105423
for 69.01 ==>>  loss:27.12916360795498
for 70.01 ==>>  loss:25.468436151742935
for 71.01 ==>>  loss:24.05219391733408
for 72.01 ==>>  loss:26.376807123422623
for 73.01 ==>>  loss:25.411043368234232
for 74.01 ==>>  loss:25.72193841636181
for 75.01 ==>>  loss:25.036074690520763
for 76.01 ==>>  loss:22.605601608753204
for 77.01 ==>>  loss:22.46696973592043
for 78.01 ==>>  loss:22.685054048895836
for 79.01 ==>>  loss:26.33975912630558
for 80.01 ==>>  loss:25.204085305333138
for 81.01 ==>>  loss:25.00835594534874
for 82.01 ==>>  loss:25.53372097015381
for 83.01 ==>>  loss:26.13556382060051
for 84.01 ==>>  loss:26.29719664156437
for 85.01 ==>>  loss:44.66986083984375
for 86.01 ==>>  loss:29.383571535348892
for 87.01 ==>>  loss:24.57179167866707
for 88.01 ==>>  loss:22.58600626885891
for 89.01 ==>>  loss:33.054055362939835
for 90.01 ==>>  loss:38.7129916921258
for 91.01 ==>>  loss:21.393254444003105
for 92.01 ==>>  loss:18.411839097738266
for 93.01 ==>>  loss:22.581813253462315
for 94.01 ==>>  loss:25.653022661805153
for 95.01 ==>>  loss:23.89106546342373
for 96.01 ==>>  loss:23.351539123803377
for 97.01 ==>>  loss:27.012492336332798
for 98.01 ==>>  loss:24.295936800539494
for 99.01 ==>>  loss:20.019997384399176

In [28]:
# evaluation
total=0
correct=0
model.eval()
with torch.no_grad():
  for xb,yb in test_dataloader:
    output=model(xb)
    _,predicted=torch.max(output,1)
    correct+=(predicted==yb).sum().item()
    total+=yb.size(0)



  print(total)
  print(correct)

180
128

In [29]:
accuracy=correct/total*100
print(accuracy)

71.11111111111111